apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: database
  labels:
    app: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
      annotations:
          ad.datadoghq.com/postgres-db-container.logs: '[{"source": "postgresql", "service": "postgres-db", "tags":["runtime:kubernetes"]}]'
    spec:
      containers:
      - name: postgres-db-container
        image: postgres:13
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: database
              key: db-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database
              key: db-password
        volumeMounts:
          - name: sql-script
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: sql-script
          configMap:
            name: sql-script
            items: 
              - key: create-table.sql
                path: create-table.sql
