apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-store
  namespace: go-web-store
  labels:
    app: go-web-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web-store
  template:
    metadata:
      labels:
        app: go-web-store
      annotations:
        ad.datadoghq.com/go-web-store.logs: '[{"source": "go", "service": "go-store", "tags":["runtime:kubernetes"]}]'
    spec:
      containers:
      - name: go-web-store-container
        image: uehara96/app-golang:latest
        env:
        - name: DD_SERVICE
          value: "go-store"
        - name: DD_VERSION
          value: "1.1"
        - name: DD_ENV
          value: "local"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database
              key: db-user
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: database
              key: db-name
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: database
              key: db-host
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database
              key: db-password
        ports:
        - containerPort: 8080
