registry: gcr.io/datadoghq
datadog:
  apiKeyExistingSecret: datadog-secret
  site: datadoghq.com
  tags:
    - env:local
  logs:
    enabled: true
    containerCollectAll: true
  processAgent:
    enabled: true
    processCollection: true
  kubelet:
    tlsVerify: false
